services:
  unbound:
    image: resolver-lab/unbound:1.23.0
    build:
      context: unbound
      args:
        VERSION: 1.23.0
    container_name: unbound
    environment:
      CONFIG: default
    tty: true
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.1
#===============================================
  bind:
    image: resolver-lab/bind:9.20.9
    build:
      context: bind
      args:
        VERSION: 9.20.9
    container_name: bind
    environment:
      CONFIG: default
    tty: true
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.2
#===============================================
  knot:
    image: resolver-lab/knot:5.7.5
    build:
      context: knot
      args:
        VERSION: 5.7.5
    container_name: knot
    environment:
      CONFIG: default
    tty: true
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.3
#===============================================
#  powerdns:
#    image: resolver-lab/powerdns:5.2.2
#    build:
#      context: powerdns
#      args:
#        VERSION: 5.2.2
#    container_name: powerdns
#    environment:
#      CONFIG: default
#    tty: true
#    networks:
#      resolver-lab:
#        ipv4_address: 10.0.53.4
#===============================================
  egress:
    image: resolver-lab/unbound:1.23.0
    build:
      context: unbound
      args:
        VERSION: 1.23.0
    container_name: egress
    environment:
      CONFIG: qmin-off
    tty: true
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.5
#===============================================
  fpdns:
    image: resolver-lab/fpdns.lab
    build: fpdns.lab
    container_name: fpdns.lab
    tty: true
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.6
#===============================================
  oldqmin:
    image: resolver-lab/qmin.lab
    build: qmin.lab
    container_name: oldqmin.lab
    environment:
      VERSION: old
    tty: true
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.7 # and 10.0.53.8
    cap_add:
      - NET_ADMIN # add two IPv4 addresses within container
#===============================================
  newqmin:
    image: resolver-lab/qmin.lab
    build: qmin.lab
    container_name: newqmin.lab
    environment:
      VERSION: new
    tty: true
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.9 # and 10.0.53.10
    cap_add:
      - NET_ADMIN # add two IPv4 addresses within container
#===============================================
  polar:
    image: resolver-lab/polar.lab
    build: polar.lab
    container_name: polar.lab
    tty: true
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.11
#===============================================
  ns1:
    image: resolver-lab/ns1.lab
    build: ns1.lab
    container_name: ns1.lab
    tty: true
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.53
#===============================================
  iodine-server:
    image: resolver-lab/iodine.lab
    build:
      context: iodine.lab
      args:
        VERSION: 0.7.0
    container_name: iodine-server
    environment:
      ROLE: server
      TOPDOMAIN: iodine.lab
      TUNNEL_IP: 172.16.53.1
      PASSWORD: secretpassword
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    tty: true
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.12
  #===============================================
  iodine-client:
    image: resolver-lab/iodine.lab
    build:
      context: iodine.lab
      args:
        VERSION: 0.7.0
    container_name: iodine-client
    environment:
      ROLE: client
      SERVER_IP: 10.0.53.1 #10.0.53.12
      TOPDOMAIN: iodine.lab
      PASSWORD: secretpassword
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    tty: true
    depends_on:
      - iodine-server
    networks:
      resolver-lab:
        ipv4_address: 10.0.53.13
#===============================================
networks:
  resolver-lab:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
